name: GitHub Action
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14

      - name: checkout out code
        uses: actions/checkout@v2

      - name: install dependency
        run: yarn

      - name: run bin/build.sh
        run: sh bin/build.sh
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

